---
- name: Create and manage Proxmox LXC container
  hosts: "{{ host }}"
  gather_facts: false
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Create LXC container
      community.general.proxmox:
        api_user: "{{ user }}"
        api_token_id: "{{ token_id }}"
        api_token_secret: "{{ token_secret }}"
        api_host: "{{ host }}"
        node: "{{ node }}"
        hostname: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=6') }}"
        ostemplate: "local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst"
        cores: 1
        memory: 512
        swap: 512
        disk: "VM:5"                  
        password: "{{ lxc_password }}"
        netif:
          net0: "name=eth0,ip=dhcp,bridge=vmbr0,firewall=0"
        features: 
          - nesting=1
        timeout: 600
      delegate_to: localhost
      register: container

    - name: Start the LXC container
      community.general.proxmox:
        api_user: "{{ user }}"
        api_token_id: "{{ token_id }}"
        api_token_secret: "{{ token_secret }}"
        api_host: "{{ host }}"
        vmid: "{{ container.id | default(container.vmid) }}"
        node: "{{ node }}"
        state: started
      delegate_to: localhost
