---
- name: Create and manage Proxmox LXC container
  hosts: "{{ host }}"
  gather_facts: false
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Generate random hostname
      set_fact:
        random_hostname: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=6') }}"

    - name: Create container
      community.general.proxmox:
        api_user: "{{ user }}"
        api_token_id: "{{ token_id }}"
        api_token_secret: "{{ token_secret }}"
        api_host: "{{ host }}"
        node: "{{ node }}"
        hostname: "{{ random_hostname }}"
        ostemplate: "local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst"
        cores: 1
        memory: 512
        swap: 512
        mounts: {rootfs: "VM:5"}
        password: "{{ lxc_password }}"
        netif: {net0: "name=eth0,ip=dhcp,bridge=vmbr0,firewall=0"}
        features: "nesting=1"
      delegate_to: localhost
      register: container

    - name: Extract VMID of the newly created container
      set_fact:
        new_container_vmid: "{{ container.id | default(container.vmid) }}"
        
    - name: Start container
      community.general.proxmox:
        api_user: "{{ user }}"
        api_token_id: "{{ token_id }}"
        api_token_secret: "{{ token_secret }}"
        api_host: "{{ host }}"
        vmid: "{{ new_container_vmid }}"
        node: "{{ node }}"
        state: started
      delegate_to: localhost

    - name: Wait for SSH port
      wait_for:
        port: "{{ ansible_port | default(22) }}"
        host: "{{ ansible_host }}"
        timeout: 30  # seconds
      delegate_to: localhost

    - name: Gather facts
      ansible.builtin.setup:
